// https://en.bitcoin.it/wiki/Script
module.exports = [
    { name: "OP_FALSE", decValue: 0 },
    { name: "OP_0", decValue: 0 },
    { name: "OP_PUSHDATA1", decValue: 76 },
    { name: "OP_PUSHDATA2", decValue: 77 },
    { name: "OP_PUSHDATA4", decValue: 78 },
    { name: "OP_1NEGATE", decValue: 79 },
    { name: "OP_RESERVED", decValue: 80 },
    { name: "OP_TRUE", decValue: 81 },
    { name: "OP_1", decValue: 81 },
    { name: "OP_2", decValue: 82 },
    { name: "OP_3", decValue: 83 },
    { name: "OP_4", decValue: 84 },
    { name: "OP_5", decValue: 85 },
    { name: "OP_6", decValue: 86 },
    { name: "OP_7", decValue: 87 },
    { name: "OP_8", decValue: 88 },
    { name: "OP_9", decValue: 89 },
    { name: "OP_10", decValue: 90 },
    { name: "OP_11", decValue: 91 },
    { name: "OP_12", decValue: 92 },
    { name: "OP_13", decValue: 93 },
    { name: "OP_14", decValue: 94 },
    { name: "OP_15", decValue: 95 },
    { name: "OP_16", decValue: 96 },

    { name: "OP_NOP", decValue: 97 },
    { name: "OP_VER", decValue: 98 },
    { name: "OP_IF", decValue: 99 },
    { name: "OP_NOTIF", decValue: 100 },
    { name: "OP_VERIF", decValue: 101 },
    { name: "OP_VERNOTIF", decValue: 102 },
    { name: "OP_ELSE", decValue: 103 },
    { name: "OP_ENDIF", decValue: 104 },
    { name: "OP_VERIFY", decValue: 105 },
    { name: "OP_RETURN", decValue: 106 },

    { name: "OP_TOALTSTACK", decValue: 107 },
    { name: "OP_FROMALTSTACK", decValue: 108 },
    { name: "OP_2DROP", decValue: 109 },
    { name: "OP_2DUP", decValue: 110 },
    { name: "OP_3DUP", decValue: 111 },
    { name: "OP_2OVER", decValue: 112 },
    { name: "OP_2ROT", decValue: 113 },
    { name: "OP_2SWAP", decValue: 114 },
    { name: "OP_IFDUP", decValue: 115 },
    { name: "OP_DEPTH", decValue: 116 },
    { name: "OP_DROP", decValue: 117 },
    { name: "OP_DUP", decValue: 118 },
    { name: "OP_NIP", decValue: 119 },
    { name: "OP_OVER", decValue: 120 },
    { name: "OP_PICK", decValue: 121 },
    { name: "OP_ROLL", decValue: 122 },
    { name: "OP_ROT", decValue: 123 },
    { name: "OP_SWAP", decValue: 124 },
    { name: "OP_TUCK", decValue: 125 },

    { name: "OP_CAT", decValue: 126 },
    { name: "OP_SUBSTR", decValue: 127 },
    { name: "OP_LEFT", decValue: 128 },
    { name: "OP_RIGHT", decValue: 129 },
    { name: "OP_SIZE", decValue: 130 },

    { name: "OP_INVERT", decValue: 131 },
    { name: "OP_AND", decValue: 132 },
    { name: "OP_OR", decValue: 133 },
    { name: "OP_XOR", decValue: 134 },
    { name: "OP_EQUAL", decValue: 135 },
    { name: "OP_EQUALVERIFY", decValue: 136 },
    { name: "OP_RESERVED1", decValue: 137 },
    { name: "OP_RESERVED2", decValue: 138 },

    { name: "OP_1ADD", decValue: 139 },
    { name: "OP_1SUB", decValue: 140 },
    { name: "OP_2MUL", decValue: 141 },
    { name: "OP_2DIV", decValue: 142 },
    { name: "OP_NEGATE", decValue: 143 },
    { name: "OP_ABS", decValue: 144 },
    { name: "OP_NOT", decValue: 145 },
    { name: "OP_0NOTEQUAL", decValue: 146 },
    { name: "OP_ADD", decValue: 147 },
    { name: "OP_SUB", decValue: 148 },
    { name: "OP_MUL", decValue: 149 },
    { name: "OP_DIV", decValue: 150 },
    { name: "OP_MOD", decValue: 151 },
    { name: "OP_LSHIFT", decValue: 152 },
    { name: "OP_RSHIFT", decValue: 153 },

    { name: "OP_BOOLAND", decValue: 154 },
    { name: "OP_BOOLOR", decValue: 155 },
    { name: "OP_NUMEQUAL", decValue: 156 },
    { name: "OP_NUMEQUALVERIFY", decValue: 157 },
    { name: "OP_NUMNOTEQUAL", decValue: 158 },
    { name: "OP_LESSTHAN", decValue: 159 },
    { name: "OP_GREATERTHAN", decValue: 160 },
    { name: "OP_LESSTHANOREQUAL", decValue: 161 },
    { name: "OP_GREATERTHANOREQUAL", decValue: 162 },
    { name: "OP_MIN", decValue: 163 },
    { name: "OP_MAX", decValue: 164 },

    { name: "OP_WITHIN", decValue: 165 },

    { name: "OP_RIPEMD160", decValue: 166 },
    { name: "OP_SHA1", decValue: 167 },
    { name: "OP_SHA256", decValue: 168 },
    { name: "OP_HASH160", decValue: 169 },
    { name: "OP_HASH256", decValue: 170 },
    { name: "OP_CODESEPARATOR", decValue: 171 },
    { name: "OP_CHECKSIG", decValue: 172 },
    { name: "OP_CHECKSIGVERIFY", decValue: 173 },
    { name: "OP_CHECKMULTISIG", decValue: 174 },
    { name: "OP_CHECKMULTISIGVERIFY", decValue: 175 },

    { name: "OP_NOP1", decValue: 176 },

    { name: "OP_NOP2", decValue: 177 },
    { name: "OP_CHECKLOCKTIMEVERIFY", decValue: 177 },

    { name: "OP_NOP3", decValue: 178 },
    { name: "OP_CHECKSEQUENCEVERIFY", decValue: 178 },

    { name: "OP_NOP4", decValue: 179 },
    { name: "OP_NOP5", decValue: 180 },
    { name: "OP_NOP6", decValue: 181 },
    { name: "OP_NOP7", decValue: 182 },
    { name: "OP_NOP8", decValue: 183 },
    { name: "OP_NOP9", decValue: 184 },
    { name: "OP_NOP10", decValue: 185 },

    { name: "OP_PUBKEYHASH", decValue: 253 },
    { name: "OP_PUBKEY", decValue: 254 },
    { name: "OP_INVALIDOPCODE", decValue: 255 }
];